name: Dependabot Auto Sync (manifest)

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  sync-manifest:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install packaging

      - name: Sync manifest requirements with pyproject/uv.lock
        run: |
          python scripts/sync_manifest_requirements.py || true
          if ! git diff --quiet -- custom_components/escpos_printer/manifest.json; then
            echo "Changes detected in manifest.json; committing..."
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add custom_components/escpos_printer/manifest.json
            git commit -m "chore(dependabot): sync manifest requirements"
            git push
          else
            echo "No manifest changes needed."
          fi

