name: Hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
